---
title: "mega-lcwgs-pw-fst-snakeflow"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a simple Snakemake workflow for calculating pairwise Fsts (and related
quantities, eventually, I suppose) from BAM files using ANGSD. 

Note that the `mega` in the name doesn't refer to anything that I think is
"millions-esque" about this project.  It is simply one of the workflows we use in
the **M**olecular **E**cology and **G**enetic **A**nalysis (MEGA) Team at
NOAA's Southwest Fisheries Science, Fisheries Ecology Division.

Setting up this workflow for yourself is pretty easy:

1. You have to put appropriate values in the config file for your
own data set
2. You need a `bams.tsv` file that gives that paths to the BAM files
and tells what group (population) each such sample/bam belongs to.
**Spaces are not allowed in the bam file paths.**
3. You need a `pwcomps.tsv` that lists the pairwise comparisons
from the groups in `bams.tsv` that you wish to calculate pairwise
Fsts for. 